openapi: 3.0.3
info:
  title: EntitySets API
  version: "-"
  description: APIs to manage entity sets
tags:
  - name: Entity Set
    description: |
      A dynamic set allows you to define a search expression that returns a set of elements of an entity (for example a list of customers that satisfy a set of 
      conditions). Dynamic sets are used when it is necessary to define a set of customers or products based on their characteristics. 
      The dynamism depends on the fact that the elements included in the set are determined when the extraction of the set is requested and depend on the given
      values.
components:
  schemas:
    #
    # Enums.
    #
    LogicOperatorId:
      description: The logic operator. See dictionary `LogicOperator`.
      type: string
      enum:
        - LogicOperator.AND
        - LogicOperator.OR
    ConditionOperatorId:
      description: The condition operator. See dictionary `ConditionOperator`.
      type: string
      enum:
        - ConditionOperator.BL
        - ConditionOperator.BW
        - ConditionOperator.EQ
        - ConditionOperator.GT
        - ConditionOperator.GE
        - ConditionOperator.IN
        - ConditionOperator.LT
        - ConditionOperator.LE
        - ConditionOperator.NE
    #
    # EntitySetCondition objects.
    #
    EntitySetCondition:
      description: EntitySetCondition resource.
      type: object
      required:
        - type
        - id
        - attributes
        - relationships
      properties:
        type:
          type: string
          default: "EntitySetCondition"
        id:
          type: string
        attributes:
          type: object
          required:
            - value
          properties:
            logicOperatorId:
              $ref: "#/components/schemas/LogicOperatorId"
            conditionOperatorId:
              $ref: "#/components/schemas/ConditionOperatorId"
            value:
              type: string
              description: Condition value. Can be a single value or a sequence of values (used with in operator).
            children:
              type: array
              items:
                $ref: "#/components/schemas/EntitySetCondition"
        relationships:
          type: object
          description: |
            An EntitySetCondition relates to an entity attribute.
          required:
            - entityAttribute
          properties:
            entityAttribute:
              $ref: "./jsonapi.yaml#/components/schemas/relToOne"
    #
    # EntitySet objects.
    #
    EntitySet:
      description: EntitySet resource.
      type: object
      required:
        - type
        - id
        - attributes
        - relationships
      properties:
        type:
          type: string
          default: "EntitySet"
        id:
          type: string
        attributes:
          type: object
          required:
            - entitySetTypeId
            - descr
            - private
          properties:
            entitySetTypeId:
              description: The related entity type.
              type: string
              pattern: "^(CustomerAccount|Item)$"
            descr:
              description: EntitySet description.
              type: string
            private:
              description: True if the set is private and can only be used by the owner.
              type: boolean
            expression:
              description: Read only attribute. Represent the resulting statement of the given conditions.
              type: string
              readOnly: true
        relationships:
          type: object
          description: |
            The relationships of the EntitySet. An EntitySet refers to a user profile that owns it.
          required:
            - ownerUserProfile
          properties:
            ownerUserProfile:
              $ref: "./jsonapi.yaml#/components/schemas/relToOne"
            rootCondition:
              $ref: "./jsonapi.yaml#/components/schemas/relToOne"
    EntitySetIncluded:
      description: The owner of the entity set, the related conditions and entity attribute.
      type: array
      items:
        type: object
      uniqueItems: true
    EntitySetResponse:
      description: Single EntitySet response.
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/EntitySet"
        included:
          $ref: "#/components/schemas/EntitySetIncluded"
    EntitySetListResponse:
      type: object
      required:
        - data
        - meta
      properties:
        data:
          description: List of EntitySet
          type: array
          items:
            $ref: "#/components/schemas/EntitySet"
        meta:
          $ref: "./jsonapi.yaml#/components/schemas/PaginationMeta"
        links:
          $ref: "./jsonapi.yaml#/components/schemas/pagination"
        included:
          $ref: "#/components/schemas/EntitySetIncluded"
  parameters:
    id:
      name: id
      in: path
      description: The entity set id
      required: true
      schema:
        type: string
paths:
  /entity-sets:
    get:
      description: Returns a list of all entity sets.
      operationId: listEntitySets
      tags:
        - Entity Set
      x-authorities:
        - apiUser
      parameters:
        - $ref: "./jsonapi.yaml#/components/parameters/pageSize"
        - $ref: "./jsonapi.yaml#/components/parameters/pageNumber"
        - $ref: "./jsonapi.yaml#/components/parameters/sort"
        - $ref: "./jsonapi.yaml#/components/parameters/include"
        - $ref: "./jsonapi.yaml#/components/parameters/acceptLanguage"
        - name: "filter"
          in: query
          description: Filter group
          required: true
          style: deepObject
          schema:
            type: object
            properties:
              s:
                description: Search the given string; searches inside some attributes, as specified in the API documentation, e.g. descr, code, etc.
                type: string
              entitySetType:
                description: Filter the response by entity set type.
                type: string
              ownerUserProfile:
                description: Filter the response by owner user profile.
                type: string
              private:
                description: Filter the response by private flag.
                type: string
      responses:
        "200":
          description: EntitySet list response.
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/EntitySetListResponse"
        "400":
          description: Bad request.
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
  /entity-sets/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      description: Returns a single entity set.
      operationId: getEntitySet
      tags:
        - Entity Set
      x-authorities:
        - apiUser
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/EntitySetResponse"
        "404":
          description: "[Not found](https://jsonapi.org/format/#fetching-resources-responses-404)"
