openapi: 3.0.3
info:
  title: Grey market related APIs.
  version: "-"
  description: APIs related to grey market.
tags:
  - name: Grey Market Survey
components:
  parameters:
    SurveyHeaderId:
      name: headerId
      in: path
      description: The survey header id
      required: true
      schema:
        type: string
    SurveyLineId:
      name: lineId
      in: path
      description: The survey line id
      required: true
      schema:
        type: string
  schemas:
    ReadingMethod:
      description: |
        An enumeration that defines a mean of data acquisition. The possible values are:
        * `ReadingMethod.Manual`, used when data is acquired manually by the user;
        * `ReadingMethod.NFC`, used when data is acquired by scanning a NFC tag;
        * `ReadingMethod.QRCode`, used when data is acquired by reading a QRCode or a barcode;
        * `ReadingMethod.UHF`, used when data is acquired by reading an UHF tag;
        * `ReadingMethod.Hybrid`, used when data is acquired with any combination of the above methods.
      type: string
      enum:
        - ReadingMethod.Manual
        - ReadingMethod.NFC
        - ReadingMethod.QRCode
        - ReadingMethod.UHF
        - ReadingMethod.Hybrid
      x-enum-varnames:
        - manual
        - nfc
        - qrCode
        - uhf
        - hybrid
    GreyMarketSurveyHeaderAttributes:
      description: The attributes of a `GreyMarketSurveyHeader` resource.
      type: object
      required:
        - startTs
        - totItems
        - processingStatusId
      properties:
        startTs:
          description: The date and time at which the grey market survey started.
          allOf:
            - $ref: "./dataTypes.yaml#/components/schemas/apiDateTime"
        endTs:
          description: The date and time at which the grey market survey finished.
          allOf:
            - $ref: "./dataTypes.yaml#/components/schemas/apiDateTime"
        descr:
          description: |
            An open description of the grey market survey. Usually, it corresponds to the business name of
            the place for which the survey is done.
          type: string
          example: "Autostore Benetton Castrette di Villorba (TV) 31100 Italia"
        addressDescr:
          description: The address where the grey market survey took place.
          type: string
          example: "Via Alessandro Volta, 31/A"
        latitude:
          description: The latitude of the place where the grey market survey took place.
          type: number
          format: double
          example: 45.72555
        longitude:
          description: The longitude of the place where the grey market survey took place.
          type: number
          format: double
          example: 12.25285
        readingMethodId:
          description: The overall technology/method by which the grey market survey's lines were acquired. See `ReadingMethod` dictionary.
          allOf:
            - $ref: "#/components/schemas/ReadingMethod"
        processingStatusId:
          description: A status that defines if the survey header was transmitted or not to the server. See `ProcessingStatus` dictionary.
          allOf:
            - $ref: "./core.yaml#/components/schemas/ProcessingStatus"
        totItems:
          description: The total amount of items that belong to the header.
          type: integer
          minimum: 0
          default: 0
    #
    # GreyMarketSurveyHeaderRelationships
    #
    GreyMarketSurveyHeaderRelationships:
      description: Related schemas of a `GreyMarketSurveyHeader`resource.
      type: object
      required:
        - organization
        - language
      properties:
        organization:
          $ref: "./jsonapi.yaml#/components/schemas/relToOne"
        userProfile:
          $ref: "./jsonapi.yaml#/components/schemas/relToOne"
        device:
          $ref: "./jsonapi.yaml#/components/schemas/relToOne"
        language:
          $ref: "./jsonapi.yaml#/components/schemas/relToOne"
    #
    # GreyMarketSurveyHeader
    #
    GreyMarketSurveyHeader:
      description: A grey market survey which represents a study done to collect items data in a particular location.
      type: object
      required:
        - type
        - id
        - attributes
        - relationships
      properties:
        type:
          description: A string that describes the type of the object.
          type: string
          default: "GreyMarketSurveyHeader"
        id:
          description: A string that uniquely identify the object.
          type: string
          example: "GM.SURVEY.1"
        attributes:
          $ref: "#/components/schemas/GreyMarketSurveyHeaderAttributes"
        relationships:
          $ref: "#/components/schemas/GreyMarketSurveyHeaderRelationships"
    #
    # GreyMarketSurveyHeaderIncluded
    #
    GreyMarketSurveyHeaderIncluded:
      description: The set of `GreyMarketSurveyHeader` related schemas.
      type: array
      items:
        type: object
      uniqueItems: true
    #
    # GreyMarketSurveyHeaderListResponse
    #
    GreyMarketSurveyHeaderListResponse:
      description: An object that contains a list of `GreyMarketSurveyHeader` resources.
      type: object
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/GreyMarketSurveyHeader"
        meta:
          $ref: "./jsonapi.yaml#/components/schemas/PaginationMeta"
        links:
          $ref: "./jsonapi.yaml#/components/schemas/pagination"
        included:
          $ref: "#/components/schemas/GreyMarketSurveyHeaderIncluded"
    #
    # GreyMarketSurveyHeaderResponse
    #
    GreyMarketSurveyHeaderResponse:
      description: An object that contains a `GreyMarketSurveyHeader` resource.
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/GreyMarketSurveyHeader"
        included:
          $ref: "#/components/schemas/GreyMarketSurveyHeaderIncluded"
    #
    # GreyMarketSurveyHeaderRequest
    #
    GreyMarketSurveyHeaderRequest:
      description: An object that contains a `GreyMarketSurveyHeader` resource.
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/GreyMarketSurveyHeader"
    #
    # GreyMarketSurveyLineAttributes
    #
    GreyMarketSurveyLineAttributes:
      description: The attributes of a `GreyMarketSurveyLine` resource.
      type: object
      required:
        - lineNumber
        - creationTs
        - readingMethodId
      properties:
        lineNumber:
          description: An integer and progressive number used to define a sorting criteria on the lines.
          type: string
          readOnly: true
          example: "1"
        creationTs:
          description: The date and time when the survey line was created.
          allOf:
            - $ref: "./dataTypes.yaml#/components/schemas/apiDateTime"
        readingMethodId:
          description: The technology/method by which the line was acquired. See `ReadingMethod` dictionary.
          allOf:
            - $ref: "#/components/schemas/ReadingMethod"
        epc:
          description: Not `null` when the line represents an UHF acquisition. In particular, it is the EPC of the read UHF tag.
          type: string
          example: "0002001C0011B27A51385A18"
        fullContentNfc:
          description: Not `null` when the line represents a NFC acquisition. In particular, it is the content of the read NFC tag.
          type: string
          example: "https://aton.com/nfc-content"
        fullContentBarcode:
          description: Not `null` when the line represents a QRCode or barcode acquisition. In particular, it is the content of the read QR/barcode.
          type: string
          example: "A-85971233"
        item:
          description: The item linked to the survey line. It could be `null` when it was not possible to recognize an item during line's acquisition.
          $ref: "./core.yaml#/components/schemas/SimpleEntityReadOnly"
    #
    # GreyMarketSurveyLineRelationships
    #
    GreyMarketSurveyLineRelationships:
      description: Related schemas of a `GreyMarketSurveyLine`resource.
      type: object
      required:
        - greyMarketSurveyHeader
      properties:
        greyMarketSurveyHeader:
          $ref: "./jsonapi.yaml#/components/schemas/relToOneReadOnly"
        itemInstance:
          $ref: "./jsonapi.yaml#/components/schemas/relToOne"
    #
    # GreyMarketSurveyLine
    #
    GreyMarketSurveyLine:
      description: A grey market survey line. It represents a single acquisition done during a survey.
      type: object
      required:
        - type
        - id
        - attributes
        - relationships
      properties:
        type:
          description: A string that describes the type of the object.
          type: string
          default: "GreyMarketSurveyLine"
        id:
          description: A string that uniquely identify the object.
          type: string
          example: "GM.LINE.1"
        attributes:
          $ref: "#/components/schemas/GreyMarketSurveyLineAttributes"
        relationships:
          $ref: "#/components/schemas/GreyMarketSurveyLineRelationships"
    #
    # GreyMarketSurveyLineIncluded
    #
    GreyMarketSurveyLineIncluded:
      description: The set of `GreyMarketSurveyLine` related schemas.
      type: array
      items:
        type: object
      uniqueItems: true
    #
    # GreyMarketSurveyLineListResponse
    #
    GreyMarketSurveyLineListResponse:
      description: An object that contains a `GreyMarketSurveyLine`resource.
      type: object
      required:
        - data
        - meta
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/GreyMarketSurveyLine"
        meta:
          $ref: "./jsonapi.yaml#/components/schemas/PaginationMeta"
        links:
          $ref: "./jsonapi.yaml#/components/schemas/pagination"
        included:
          $ref: "#/components/schemas/GreyMarketSurveyLineIncluded"
    #
    # GreyMarketSurveyLineListRequest
    #
    GreyMarketSurveyLineListRequest:
      description: An object that contains a list of `GreyMarketSurveyLine`resources.
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/GreyMarketSurveyLine"
    #
    # GreyMarketSurveyLineResponse
    #
    GreyMarketSurveyLineResponse:
      description: An object that contains a list of `GreyMarketSurveyLine`resources.
      type: object
      required:
        - data
      properties:
        data:
          $ref: "#/components/schemas/GreyMarketSurveyLine"
        included:
          $ref: "#/components/schemas/GreyMarketSurveyLineIncluded"
#
# Paths
#
paths:
  /grey-market-surveys/headers:
    parameters:
      - $ref: "./jsonapi.yaml#/components/parameters/acceptLanguage"
    get:
      description: Returns a list of `GreyMarketSurveyHeader` resources.
      operationId: listGreyMarketSurveyHeaders
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      parameters:
        - $ref: "./jsonapi.yaml#/components/parameters/pageSize"
        - $ref: "./jsonapi.yaml#/components/parameters/pageNumber"
        - $ref: "./jsonapi.yaml#/components/parameters/sort"
        - $ref: "./jsonapi.yaml#/components/parameters/include"
        - $ref: "./core.yaml#/components/parameters/filterOrganizationRequired"
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyHeaderListResponse"
        "400":
          description: Bad request.
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
    post:
      description: Creates a new `GreyMarketSurveyHeader` resource.
      operationId: createGreyMarketSurveyHeader
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      requestBody:
        description: A `GreyMarketSurveyHeader` to post.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/GreyMarketSurveyHeaderRequest"
      responses:
        "201":
          description: "[Created](https://jsonapi.org/format/#crud-creating-responses-201)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyHeaderResponse"
        "400":
          description: Bad request.
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
  /grey-market-surveys/headers/{headerId}:
    parameters:
      - $ref: "#/components/parameters/SurveyHeaderId"
      - $ref: "./jsonapi.yaml#/components/parameters/acceptLanguage"
    get:
      description: Returns a `GreyMarketSurveyHeader` resource.
      operationId: getGreyMarketSurveyHeader
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyHeaderResponse"
        "404":
          description: "[Not found](https://jsonapi.org/format/#fetching-resources-responses-404)"
    patch:
      description: Updates a `GreyMarketSurveyHeader` resource.
      operationId: updateGreyMarketSurveyHeader
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      requestBody:
        description: A `GreyMarketSurveyHeader` to update.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/GreyMarketSurveyHeaderRequest"
      responses:
        "200":
          description: "[Created](https://jsonapi.org/format/#crud-creating-responses-201)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyHeaderResponse"
        "400":
          description: "Bad request"
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
  /grey-market-surveys/headers/{headerId}/lines:
    parameters:
      - $ref: "#/components/parameters/SurveyHeaderId"
      - $ref: "./jsonapi.yaml#/components/parameters/acceptLanguage"
    get:
      description: Returns a list of `GreyMarketSurveyLine` resources.
      operationId: listGreyMarketSurveyLine
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      parameters:
        - $ref: "./jsonapi.yaml#/components/parameters/pageSize"
        - $ref: "./jsonapi.yaml#/components/parameters/pageNumber"
        - $ref: "./jsonapi.yaml#/components/parameters/sort"
        - $ref: "./jsonapi.yaml#/components/parameters/include"
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyLineListResponse"
        "400":
          description: "Bad request"
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
    post:
      description: Creates a list of `GreyMarketSurveyLine` resources.
      operationId: createGreyMarketSurveyLines
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      requestBody:
        description: A list of `GreyMarketSurveyLine` resources to update.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: "#/components/schemas/GreyMarketSurveyLineListRequest"
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyLineListResponse"
        "400":
          description: "Bad request"
          content:
            application/vnd.api+json:
              schema:
                $ref: "./jsonapi.yaml#/components/schemas/failure"
  /grey-market-surveys/lines/{lineId}:
    parameters:
      - $ref: "#/components/parameters/SurveyLineId"
      - $ref: "./jsonapi.yaml#/components/parameters/acceptLanguage"
    get:
      description: Returns a `GreyMarketSurveyLine` resource.
      operationId: getGreyMarketSurveyLine
      tags:
        - Grey Market Survey
      x-authorities:
        - apiUser
      responses:
        "200":
          description: "[OK](https://jsonapi.org/format/#fetching-resources-responses-200)"
          content:
            application/vnd.api+json:
              schema:
                $ref: "#/components/schemas/GreyMarketSurveyLineResponse"
        "404":
          description: "[Not found](https://jsonapi.org/format/#fetching-resources-responses-404)"
